services:
  - type: web
    name: nova-medical-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
 
    plan: starter
 
    envVars:
      - key: GEMINI_API_KEY
        sync: false         
 
      - key: ANTHROPIC_API_KEY
        sync: false
 
      - key: GROQ_API_KEY
        sync: false
 
    autoDeploy: true
 
    healthCheckPath: /api/health
 
